server:
  port: 3390
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/css,text/plain
spring:
  datasource:
    name: laike_hotel
    url: jdbc:mysql://127.0.0.1:3306/laike_hotel?useUnicode=true&characterEncoding=UTF-8
    username: root
#    yml 中 纯数字密码需加""
    password: ""
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: "GMT+8"
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,classpath:/static/dist
  profiles:
    active: dev
#  thymeleaf:
#    prefix: classpath:/templates/
#  mvc:
#    static-path-pattern: /static/**


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ywt.laike.hotel.model
  configuration:
    use-generated-keys: true
    use-column-label: true
logging:
  level:
    com.ywt.laike.hotel.dao: DEBUG

---
spring:
  profiles: dev
server:
  port: 3390
---
spring:
     profiles: prod
     datasource:
       name: laike_hotel
       url: jdbc:mysql://127.0.0.1:3306/laike_hotel?useUnicode=true&characterEncoding=UTF-8
       username: 
       #    yml 中 纯数字密码需加""
       password: 
server:
  port: 80

logging:
  file: log/laike.log
